nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
        - "80:80"
        - "443:443"
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: ""
    volumes:
        - /home/shad/config/nginx-proxy/html:/usr/share/nginx/html
        - /home/shad/config/nginx-proxy/vhost.d:/etc/nginx/vhost.d
        - /home/shad/config/nginx-proxy/conf.d:/etc/nginx/conf.d
        - /home/shad/config/nginx-proxy/certs:/etc/nginx/certs:ro
        - /var/run/docker.sock:/tmp/docker.sock:ro

nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from:
        - nginx-proxy
    volumes:
        - /home/shad/config/nginx-proxy/certs:/etc/nginx/certs:rw
        - /var/run/docker.sock:/var/run/docker.sock:ro

nginx-static:
    image: nginx
    ports:
        - "61083:80"
    volumes:
        - /home/shad/www:/usr/share/nginx/html
        - /home/shad/config/nginx-static/vhosts.conf:/etc/nginx/conf.d/vhosts.conf:ro
    environment:
        - VIRTUAL_PORT=80
        - VIRTUAL_HOST=gcloud.zaphod.us
        - LETSENCRYPT_HOST=gcloud.zaphod.us
        - LETSENCRYPT_EMAIL=shad42@gmail.com
